### ISSUE TITLE
FileNotFoundError: No such file or directory: '' Error

### ISSUE THREAD

**Issue by riramos** [lablnet/Email-Spider#4]
Hi, I am trying to use on Kali Linux, when I ran the script, the following error message appears:

Creating the required directory
Traceback (most recent call last):
  File "/home/kali/Tools/Email-Spider/index.py", line 3, in <module>
    from src.main import main
  File "/home/kali/Tools/Email-Spider/src/main.py", line 30, in <module>
    EmailSpider(project_name, url, domain)
  File "/home/kali/Tools/Email-Spider/src/email_spider.py", line 30, in __init__
    EmailSpider.boot()
  File "/home/kali/Tools/Email-Spider/src/email_spider.py", line 39, in boot
    create_directory(EmailSpider.project_name)
  File "/home/kali/Tools/Email-Spider/src/helper.py", line 34, in create_directory
    os.makedirs(name)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

Regards

**Comment by lablnet** [comment]
Hello @riramos am really sorry you encounter error, and sorry for delay response.
I have check this script run fine, in Ubuntu, and in Window 
try to add following at top of `src/main.py`
```py
import sys
sys.path.append(".")
```
If still not work, let me know, thanks.

**Comment by riramos** [comment]
Hello @lablnet, I made the suggested changes, but I received the following error. I used a Ubuntu 20:
 
Creating the required directory
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    from src.main import main
  File "/home/administrator/Tools/Email-Spider/src/main.py", line 33, in <module>
    EmailSpider(project_name, url, domain)
  File "/home/administrator/Tools/Email-Spider/src/email_spider.py", line 30, in __init__
    EmailSpider.boot()
  File "/home/administrator/Tools/Email-Spider/src/email_spider.py", line 39, in boot
    create_directory(EmailSpider.project_name)
  File "/home/administrator/Tools/Email-Spider/src/helper.py", line 34, in create_directory
    os.makedirs(name)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

Regards

**Comment by lablnet** [comment]
@riramos 
In ubuntu make sure the project directory have right permission and have write permission.
try to run following command in ubuntu 
```sh
chmod 755 .
```
also add this to index.py too.
```py
import sys
sys.path.append(".")
```

Thanks for update, if still let me know, I will try to find solution and re run it to virtual machines.

**Comment by riramos** [comment]
@lablnet the problem persist

Creating the required directory
Traceback (most recent call last):
  File "index.py", line 5, in <module>
    from src.main import main
  File "/home/administrator/Tools/Email-Spider/src/main.py", line 33, in <module>
    EmailSpider(project_name, url, domain)
  File "/home/administrator/Tools/Email-Spider/src/email_spider.py", line 30, in __init__
    EmailSpider.boot()
  File "/home/administrator/Tools/Email-Spider/src/email_spider.py", line 39, in boot
    create_directory(EmailSpider.project_name)
  File "/home/administrator/Tools/Email-Spider/src/helper.py", line 34, in create_directory
    os.makedirs(name)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by lablnet** [comment]
The issue seems to with your python installations or with your system path(s).
![WhatsApp Image 2021-04-30 at 4](https://user-images.githubusercontent.com/27757785/116692637-1a0bab80-a9d6-11eb-93c1-3794445d0d37.jpg)

You need to provide either more info or try to google it and solve it, you are welcome to sent `PR`

**Comment by masked-man307** [comment]
Pls when i try to do a do a clone on kali linux it tells me no such file or directory how can i fix that pls

**Comment by lablnet** [comment]
> ### **[masked-man307](/masked-man307) ** commented [11 hours ago](#issuecomment-1254034135)

Kindly explain in more detail what do you mean by this?
- In order to make it more clear, tell the `ways` you try to clone and run the script.

Thanks.
